# Python CircleCI 2.1 configuration file.
version: 2.1
orbs:
  gcp-gke: circleci/gcp-gke@1.0.4
  go: circleci/go@1.3.0
  codecov: codecov/codecov@1.1.0

trigger:
  tags:
    include:
      - '*'
  branches:
    include:
      - "master"
      - "release/*"
      - "refs/tags/*"
      - "ci/fix-docs-build"
pr:
  - "master"
  - "release/*"

# Workflow Steps:
#  1. Checkout
#  2. Install GO
#  3. Checkout ml-testing-accelerators
#  4. GCP GKE install
#  5. Update Kubeconfig with credintials
#  6. Install jsonnet
#  7. Update jsonnet
#  8. Deploy the job on the kubernetes cluster
#  9. Statistics
#  10. Upload coverage results
#  11. Upload coverage to Codecov

references:

  make_docs: &make_docs
    run:
      name: Make Documentation
      command: |
        python --version
        pip install -e . -r requirements/pytorch/docs.txt --find-links https://download.pytorch.org/whl/cpu/torch_stable.html
        apt-get update
        apt-get upgrade -y
        apt-get install -y texlive-latex-extra dvipng texlive-pictures
        pip list
        cd docs
        make clean
        make html --jobs 2 SPHINXOPTS="-W"

jobs:
  build-Docs:
    docker:
      - image: python:3.8-bullseye
    steps:
      - checkout
      - run:
          command: |
            git submodule update --init --recursive
          name: Init git submodule
      - *make_docs
      - store_artifacts:
          # allows us to preview the generated html pages
          path: docs/build/html/
          destination: html

workflows:
  version: 2
  build-docs:
    jobs:
      - build-Docs
