name: cloud-testing

# Used to run the e2e tests on lightning.ai

on: # Trigger the workflow on push or pull request, but only for the master branch
  push:
    branches:
      - "master"
  pull_request:
    paths:
      - "src/lightning_app/**"
      - "tests/tests_app_examples/**"
      - "requirements/app/**"
      - "setup.py"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  cloud-test:
    name: Cloud Test
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        app_name:
          - v0_app
          - boring_app
          - quick_start
          - template_streamlit_ui
          - template_react_ui
          - template_jupyterlab
          - idle_timeout
          - collect_failures
          - custom_work_dependencies
          - drive
          - payload
    timeout-minutes: 35
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Get PR ID
        id: PR
        run: |
          if [ -z ${{github.event.number}} ]; then
            echo "::set-output name=ID::$(date +%s)"
          else
            echo "::set-output name=ID::${{github.event.number}}"
          fi

      - name: Cache virtualenv
        id: cache-venv
        uses: actions/cache@v2
        with:
          path: ./.venv/
          key: ${{ runner.os }}-pip-${{ matrix.app_name }}-${{ hashFiles('requirements/app/base.txt', 'requirements/app/*.txt', 'src/lightning_app/__version__.py') }}
          restore-keys: ${{ runner.os }}-venv-${{ matrix.app_name }}-

      - name: Install dependencies
        shell: bash
        run: |
          python -m venv ./.venv
          source ./.venv/bin/activate
          pip --version
          python -m pip install -r requirements/app/devel.txt --no-cache --quiet --find-links https://download.pytorch.org/whl/cpu/torch_stable.html
        if: steps.cache-venv.outputs.cache-hit != 'true'

      - name: Install package
        run: |
          source ./.venv/bin/activate
          python -m pip install -e . --find-links https://download.pytorch.org/whl/cpu/torch_stable.html
        shell: bash

      - name: Cache Playwright dependencies
        id: playwright-cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ matrix.app_name }}-${{ hashFiles('requirements/app/base.txt', 'requirements/app/*.txt', 'src/lightning_app/__version__.py') }}
          restore-keys: ${{ runner.os }}-playwright-${{ matrix.app_name }}-

      - name: Install Playwright system dependencies
        shell: bash
        run: |
          source ./.venv/bin/activate
          python -m pip install playwright
          python -m playwright install --with-deps
        if: steps.playwright-cache.outputs.cache-hit != 'true'

      - name: List pip dependency
        shell: bash
        run: |
          source ./.venv/bin/activate
          pip list

      - name: Lightning Install quick-start
        shell: bash
        if: matrix.app_name == 'quick_start'
        run: |
          source ./.venv/bin/activate
          python -m lightning install app lightning/quick-start -y

      - name: Clone Template React UI Repo
        uses: actions/checkout@v3
        with:
          repository: Lightning-AI/lightning-template-react
          token: ${{ secrets.PAT_GHOST }}
          ref: 'master'
          path: examples/app_template_react_ui

      - name: Clone Template Jupyter Lab Repo
        uses: actions/checkout@v3
        with:
          repository: Lightning-AI/lightning-template-jupyterlab
          token: ${{ secrets.PAT_GHOST }}
          ref: 'master'
          path: examples/app_template_jupyterlab

      - name: Copy Template Jupyter Lab Repo tests
        shell: bash
        run: cp examples/app_template_jupyterlab/tests/test_template_jupyterlab.py tests/tests_app_examples/test_template_jupyterlab.py

      - name: Run the tests
        env:
          LAI_USER: ${{ secrets.LAI_USER }}
          LAI_PASS: ${{ secrets.LAI_PASS }}
          LIGHTNING_USER_ID: ${{ secrets.GRID_USER_ID }}
          LIGHTNING_API_KEY: ${{ secrets.LIGHTNING_API_KEY }}
          LIGHTNING_USERNAME: ${{ secrets.LIGHTNING_USERNAME }}
          LIGHTNING_CLOUD_URL: ${{ secrets.LIGHTNING_CLOUD_URL }}
          CLOUD: "1"
          VIDEO_LOCATION: ./artifacts/videos
          PR_NUMBER: ${{ steps.PR.outputs.ID }}
          TEST_APP_NAME: ${{ matrix.app_name }}
          HAR_LOCATION: ./artifacts/hars
          SLOW_MO: 50
        shell: bash
        run: |
          source ./.venv/bin/activate
          mkdir -p ${VIDEO_LOCATION}
          HEADLESS=1 python -m pytest tests/tests_app_examples/test_${{ matrix.app_name }}.py::test_${{ matrix.app_name }}_example_cloud --timeout=900 --capture=no -v --color=yes
          # Delete the artifacts if successful
          rm -r ${VIDEO_LOCATION}/${{ matrix.app_name }}

      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: test-artifacts
          path: ./artifacts/videos

      - name: Clean Previous Apps
        if: ${{ always() }}
        env:
          LAI_USER: ${{ secrets.LAI_USER }}
          LAI_PASS: ${{ secrets.LAI_PASS }}
          LIGHTNING_USER_ID: ${{ secrets.LIGHTNING_USER_ID }}
          LIGHTNING_API_KEY: ${{ secrets.LIGHTNING_API_KEY }}
          LIGHTNING_USERNAME: ${{ secrets.LIGHTNING_USERNAME }}
          LIGHTNING_CLOUD_URL: ${{ secrets.LIGHTNING_CLOUD_URL }}
          PR_NUMBER: ${{ steps.PR.outputs.ID }}
          TEST_APP_NAME: ${{ matrix.app_name }}
          GRID_USER_ID: ${{ secrets.LIGHTNING_USER_ID }}
          GRID_USER_KEY: ${{ secrets.LIGHTNING_API_KEY }}
          GRID_URL: ${{ secrets.LIGHTNING_CLOUD_URL }}
          _GRID_USERNAME: ${{ secrets.LIGHTNING_USERNAME }}
        shell: bash
        run: |
          source ./.venv/bin/activate
          time python lightning_app/testing/testing.py delete_cloud_lightning_apps
